{% set name = "sqlean.py" %}
{% set version = "3.45.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlean.py-{{ version }}.tar.gz
  sha256: 25fbf0a111856e0384dbc412156e2e688948525c7d8609dc3803512c70130740

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sqlean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nalgeon/sqlean.py
  summary: sqlite3 with extensions
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RogerHYang
