{% set name = "sqlean.py" %}
{% set version = "3.50.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlean_py-{{ version }}.tar.gz
  sha256: 8fdc25e58ee9f3de6a6c6146a158485a46811b7d27ee966d18e2e5fe9a49d31e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sqlean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nalgeon/sqlean.py
  summary: sqlite3 with extensions
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
    - axiomofjoy
    - mikeldking
    - RogerHYang
